name: Laravel Test

on:
  push:
    branches: [ 'dev' ]
  pull_request:
    branches: [ 'dev' ]

jobs:
  laravel-tests:
    name: Ejecutar Pruebas
    runs-on: ubuntu-latest
    services:
      # Label used to access the service container
      pgsql:
        # Docker Hub image
        image: 'postgres:17'
        # Provide the password for postgres
        env:
          POSTGRES_PASSWORD: 'password'
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432
      redis:
        image: 'redis:alpine'
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 6379:6379
    steps:
      - name: Clonar Repositorio
        uses: actions/checkout@v4
      - name: Configurar PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'
      - name: Instalar Dependencias
        uses: ramsey/composer-install@v3
        with:
          composer-options: '-q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist'
      - name: Copiar .env
        run: php -r "file_exists('.env') || copy('.env.example', '.env');"
      - name: Generate key
        run: php artisan key:generate
      - name: Directory Permissions
        run: chmod -R 777 storage bootstrap/cache
      - name: Ejecutar Pruebas (Tests unitarios y de características) con PHPUnit
        env:
          APP_ENV: testing
          # Database
          DB_HOST: 127.0.0.1
          DB_DATABASE: postgres
          DB_USERNAME: postgres
          DB_PASSWORD: password
          # Redis
          REDIS_HOST: 127.0.0.1
          # Other
          BCRYPT_ROUNDS: 4
          MAIL_MAILER: array
          TELESCOPE_ENABLED: false
        run: vendor/bin/phpunit
