name: Laravel Pint

on:
  pull_request:
    branches: [ 'dev' ]

jobs:
  laravel-pint:
    name: Laravel Pint
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Clonar Repositorio
        uses: actions/checkout@v4
      - name: Configurar PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'
      - name: Instalar Dependencias
        uses: ramsey/composer-install@v3
        with:
          composer-options: '-q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist'
      - name: Ejecutar Pint
        run: vendor/bin/pint
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          branch: ${{ github.head_ref }}
          commit_message: 'lint: aplicados reparaciones de pint ✨'
          commit_user_name: 'Laravel Pint'
          commit_user_email: 'github-actions@franciscosolis.cl'
          commit_author: 'Laravel Pint <github-actions@franciscosolis.cl>'
